import { GeneratedPanel } from "../types.js";
import { NotificationType } from "../components/NotificationStack.js";
import { useAutoAnalysis } from "./useAutoAnalysis.js";
import { useVideoGeneration } from "./useVideoGeneration.js";
import { useBatchImageActions } from "./useBatchImageActions.js";
import { useSingleImageEdits } from "./useSingleImageEdits.js";
import { useAppState } from "./useAppState.js";

interface UsePipelineActionsProps {
  state: ReturnType<typeof useAppState>;
  setCurrentPanelIndex: (idx: number) => void;
  setPlaybackTime: (time: number) => void;
  setStoryboardPlaying: (val: boolean) => void;
  playStoryboardAudio: (idx: number) => void;
}

export function usePipelineActions({
  state,
  setCurrentPanelIndex,
  setPlaybackTime,
  setStoryboardPlaying,
  playStoryboardAudio,
}: UsePipelineActionsProps) {
  const {
    panels,
    setPanels,
    scrapedImages,
    setScrapedImages,
    selectedScraped,
    setSelectedScraped,
    setConsoleLogs,
    addNotification,
    fetchWithInterceptor,
    targetUrl,
    selectedSource,
    selectedModel,
    frameRate,
    voiceActor,
    musicTheme,
    editingImageIdx,
    setEditingImageIdx,
    editCropTop,
    editCropBottom,
    editCropLeft,
    editCropRight,
    editAutoTrim,
    bubbleDetectionStyle,
    bubbleEraseMethod,
    bubbleSensitivity,
    bubbleDilation,
    bubbleInpaintRadius,
    activeBubbleTab,
    isCleaningBubbles,
    setIsCleaningBubbles,
    cleanProgress,
    setCleanProgress,
    bubbleCroppingImgUrl,
    setBubbleCroppingImgUrl,
    cropSensitivity,
    cropPaddingPx,
    cropBackgroundMode,
    autoSplitTallStrips,
    processingStrategy,
    aspectRatioLock,
    minPanelAreaPct,
    overlapMergeThreshold,
    useLocalCV,
    cropModel,
    cropMinHeightPx,
    cropCannyLow,
    cropCannyHigh,
    cropCloseKernelSize,
    cropGuidance,
    cropFocusMode,
    isBatchCropping,
    setIsBatchCropping,
    batchProgress,
    setBatchProgress,
    croppingImgUrl,
    setCroppingImgUrl,
    setActivePreviewTab,
    setVideoUrl,
    isScraping,
    narrationStyle,
    accumulatedTokens,
    setAccumulatedTokens,
  } = state;

  const { runBackgroundAnalysis, addPanelsToStoryboard } = useAutoAnalysis({
    panels,
    selectedModel,
    scrapedImages,
    setPanels,
    setConsoleLogs,
    addNotification,
    fetchWithInterceptor,
    setActivePreviewTab,
    narrationStyle,
    setAccumulatedTokens,
  });

  const {
    isProcessing,
    progressStatus,
    reprocessingPanelId,
    handleGenerateVideo,
    handleTriggerReprocess,
    isRendering,
    renderProgress,
    renderEtaSeconds,
    handleRenderFinalVideo,
  } = useVideoGeneration({
    panels,
    setPanels,
    setConsoleLogs,
    addNotification,
    fetchWithInterceptor,
    targetUrl,
    selectedSource,
    selectedModel,
    frameRate,
    voiceActor,
    musicTheme,
    setVideoUrl,
    setActivePreviewTab,
    narrationStyle,
    seriesTitle: state.seriesTitle,
    chapterNumber: state.chapterNumber,
    chapterTitle: state.chapterTitle,
    scrapedGenre: state.scrapedGenre,
    seriesAuthor: state.seriesAuthor,
    seriesCoverImage: state.seriesCoverImage,
    seriesSynopsis: state.seriesSynopsis,
  });

  const {
    isCleaningBubbles: _isCleaningBubbles,
    cleanProgress: _cleanProgress,
    bubbleCroppingImgUrl: _bubbleCroppingImgUrl,
    isBatchCropping: _isBatchCropping,
    batchProgress: _batchProgress,
    croppingImgUrl: _croppingImgUrl,
    handleCleanBubblesSelected,
    handleAutoCropSelected,
    handleCancelBatch,
  } = useBatchImageActions({
    selectedScraped,
    setSelectedScraped,
    scrapedImages,
    setScrapedImages,
    setPanels,
    setConsoleLogs,
    addNotification,
    fetchWithInterceptor,
    bubbleEraseMethod,
    bubbleSensitivity,
    bubbleDetectionStyle,
    bubbleDilation,
    bubbleInpaintRadius,
    cropSensitivity,
    cropBackgroundMode,
    aspectRatioLock,
    minPanelAreaPct,
    overlapMergeThreshold,
    autoSplitTallStrips,
    useLocalCV,
    selectedModel,
    cropPaddingPx,
    cropModel,
    cropMinHeightPx,
    cropCannyLow,
    cropCannyHigh,
    cropCloseKernelSize,
    cropGuidance,
    cropFocusMode,
    isCleaningBubbles,
    setIsCleaningBubbles,
    cleanProgress,
    setCleanProgress,
    bubbleCroppingImgUrl,
    setBubbleCroppingImgUrl,
    isBatchCropping,
    setIsBatchCropping,
    batchProgress,
    setBatchProgress,
    croppingImgUrl,
    setCroppingImgUrl,
  });

  const {
    mergingIndices,
    isSavingEdit,
    handleSaveEditedImage,
    handleSaveMultipleCuts,
    handleStitchWithNext,
  } = useSingleImageEdits({
    editingImageIdx,
    scrapedImages,
    setScrapedImages,
    setSelectedScraped,
    setConsoleLogs,
    addNotification,
    fetchWithInterceptor,
    editCropTop,
    editCropBottom,
    editCropLeft,
    editCropRight,
    editAutoTrim,
    addPanelsToStoryboard,
  });

  return {
    isProcessing,
    progressStatus,
    isScraping,
    mergingIndices,
    reprocessingPanelId,
    isSavingEdit,
    handleGenerateVideo,
    handleSaveEditedImage,
    handleSaveMultipleCuts,
    handleStitchWithNext,
    handleTriggerReprocess,
    isRendering,
    renderProgress,
    renderEtaSeconds,
    handleRenderFinalVideo,
    addPanelsToStoryboard,
    handleCleanBubblesSelected,
    handleAutoCropSelected,
    isCleaningBubbles,
    cleanProgress,
    bubbleCroppingImgUrl,
    isBatchCropping,
    batchProgress,
    croppingImgUrl,
    handleCancelBatch,
  };
}
