"""
backend/python/routes/health.py
─────────────────────────────────────────────────────────────────────────────
Health Check, Capability Probe, and Real-Time SSE Log Streaming routes.
─────────────────────────────────────────────────────────────────────────────
"""

import os
import sys
import time
import json
import asyncio
import platform
import logging
from typing import Optional
from fastapi import APIRouter, Request, Query, HTTPException
from fastapi.responses import JSONResponse, StreamingResponse
from pydantic import BaseModel

class CustomLogPayload(BaseModel):
    message: str
    level: str = "info"

import database.db as db
from utils.log_interceptor import get_logs, add_log_listener, remove_log_listener
from utils.cache import get_all_cache_stats

logger = logging.getLogger("anivox.routes.health")
router = APIRouter()

# Keep track of startup time globally
START_TIME = time.time()


def _check_capability(module_name: str) -> bool:
    """Returns True if the given Python module can be imported."""
    try:
        __import__(module_name)
        return True
    except ImportError:
        return False


# ─── Routes ───────────────────────────────────────────────────────────────────

@router.get("/health", summary="Health check and capability probe")
async def health():
    uptime_sec = round(time.time() - START_TIME, 1)
    h = int(uptime_sec // 3600)
    m = int((uptime_sec % 3600) // 60)
    s = int(uptime_sec % 60)

    db_status = "connected"
    db_stats = {}
    try:
        db_stats = db.get_db_stats()
    except Exception:
        db_status = "error"

    return JSONResponse(
        content={
            "success": True,
            "status": "ok",
            "service": "Anivox Computational Backend",
            "version": os.getenv("API_VERSION", "1.0.0"),
            "uptime": f"{h}h {m}m {s}s",
            "uptimeSeconds": uptime_sec,
            "database": db_status,
            "db_type": "SQLite (local)",
            "db_stats": db_stats,
            "python": sys.version.split(" ")[0],
            "platform": f"{platform.system()} {platform.machine()}",
            "capabilities": {
                "cv2":         _check_capability("cv2"),
                "PIL":         _check_capability("PIL"),
                "numpy":       _check_capability("numpy"),
                "moviepy":     _check_capability("moviepy"),
                "edge_tts":    _check_capability("edge_tts"),
                "pydub":       _check_capability("pydub"),
                "easyocr":     _check_capability("easyocr"),
                "httpx":       _check_capability("httpx"),
                "google_genai":_check_capability("google.genai"),
            },
            "env": {
                "GEMINI_API_KEY": bool(os.getenv("GEMINI_API_KEY")),
            },
        }
    )


@router.get("/system-logs", summary="JSON polling endpoint for console logs")
async def system_logs(since: int = Query(0, description="Fetch logs generated after this sequence ID")):
    try:
        logs = get_logs(since)
        return {"success": True, "logs": logs}
    except Exception as e:
        logger.error(f"Failed to fetch system logs: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/system-logs/log", summary="Post a custom log entry to system logs")
async def add_custom_log(payload: CustomLogPayload):
    try:
        vite_logger = logging.getLogger("anivox.vite")
        lvl = payload.level.upper()
        if lvl == "ERROR":
            vite_logger.error(payload.message)
        elif lvl == "WARNING" or lvl == "WARN":
            vite_logger.warning(payload.message)
        else:
            vite_logger.info(payload.message)
        return {"success": True}
    except Exception as e:
        logger.error(f"Failed to add custom log: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/system-logs/stream", summary="Server-Sent Events (SSE) real-time console log stream")
async def system_logs_stream(request: Request):
    """
    Establishes an active SSE stream tunnel to push real-time log records
    generated by python's logging handlers directly onto the client interface.
    """
    loop = asyncio.get_running_loop()

    async def log_generator():
        # 1. Send all existing history
        history = get_logs(0)
        for entry in history:
            yield f"data: {json.dumps(entry)}\n\n"

        # 2. Queue listener for new incoming logs
        queue = asyncio.Queue()

        def listener(entry):
            # Put item in queue in a thread-safe way
            loop.call_soon_threadsafe(queue.put_nowait, entry)

        add_log_listener(listener)
        try:
            while True:
                if await request.is_disconnected():
                    break
                try:
                    entry = await asyncio.wait_for(queue.get(), timeout=15.0)
                    yield f"data: {json.dumps(entry)}\n\n"
                except asyncio.TimeoutError:
                    # Keep-alive heartbeat comment
                    yield ": ping\n\n"
        finally:
            remove_log_listener(listener)

    return StreamingResponse(
        log_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no"
        }
    )


@router.get("/metrics", summary="Live server performance and cache metrics")
async def server_metrics():
    uptime_sec = round(time.time() - START_TIME, 1)
    h = int(uptime_sec // 3600)
    m = int((uptime_sec % 3600) // 60)
    s = int(uptime_sec % 60)

    mem_used = 0
    mem_total = 0
    mem_pct = "0.0%"
    
    try:
        import psutil  # Optional dependency, check if available
        process = psutil.Process(os.getpid())
        mem_used = round(process.memory_info().rss / 1024 / 1024, 2)
        mem_total = round(psutil.virtual_memory().total / 1024 / 1024, 2)
        mem_pct = f"{psutil.virtual_memory().percent}%"
    except Exception:
        # Fallback if psutil not installed
        try:
            import resource
            mem_used = round(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1024, 2)
        except Exception:
            pass

    return {
        "server": {
            "uptime": f"{h}h {m}m {s}s",
            "uptimeSeconds": uptime_sec,
            "apiVersion": os.getenv("API_VERSION", "1.0.0"),
            "pythonVersion": sys.version.split(" ")[0],
            "platform": f"{platform.system()} {platform.machine()}",
            "env": os.getenv("NODE_ENV", "development"),
        },
        "config": {
            "port": int(os.getenv("BACKEND_PORT", "5173")),
        },
        "memory": {
            "rssMB": mem_used,
            "systemTotalMB": mem_total,
            "systemUsedPct": mem_pct,
        },
        "cache": get_all_cache_stats()
    }

